/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.sql.CallableStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class Eliminar_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar_usuario
     */
    public Eliminar_usuario() {
        this.setTitle("Elimnar Cliente"); 
        initComponents();   
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEliminar = new javax.swing.JLabel();
        jEliminar_usuario = new javax.swing.JTextField();
        bEliminar = new javax.swing.JButton();
        jVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jEliminar.setText("ELIMINAR REGISTRO DE USUARIO POR ID ");

        jEliminar_usuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bEliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jVolver.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jVolver.setText("Volver");
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jEliminar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jEliminar)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEliminar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminar)
                    .addComponent(jVolver))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
        // TODO add your handling code here:
            Menu in = new Menu();
            in.setVisible(true);
            dispose();
        
        
    }//GEN-LAST:event_jVolverActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
              try {
                  
                  
                  int opc = JOptionPane.showConfirmDialog(this,"Esta seguro que desea Eliminar");
                  int id,aux;
                  id = Integer.parseInt(jEliminar_usuario.getText());
                  
                  if(opc==0){                              //SE SELECIONA OPCION ACEPTAR
                     //CONEXION A LA BASE DE DATOS 
                    Conexion conn= new Conexion();
                    Connection con =Conexion.getConexion();
                    //LLAMADO AL PROCEDIMIENTO
                    CallableStatement cstmt = con.prepareCall("{call dbo.eliminar_cliente(?,?)}"); 
                    cstmt.setInt(1,id);
                    cstmt.registerOutParameter(2, java.sql.Types.INTEGER);
                    cstmt.execute();
                    //SE ENCONTRO Y ELIMINO EL REGISTRO
                    if(cstmt.getInt(2)==1){
                       JOptionPane.showMessageDialog(this,"Se elimino correctamente el Cliente con el id " + id);
                   }
                    //NO SE ENCONTRO EL REGISTRO
                    if(cstmt.getInt(2)==0){
                        JOptionPane.showMessageDialog(this,"No se puedo encontrar en la Base de Datos el cliente con la ID :" + id);
                    }
                   
                    
                  }
                                                          //SE SELECIONA OPCION CANCELAR
                   if(opc==1){
                       JOptionPane.showMessageDialog(this,"No se elimino el Registro del Cliente con ID :" + id);  
                   }
                    
                    }catch (Exception ex){
                        System.out.println("Error."+ ex.getMessage());
                    } 
                    
                    
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_bEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JLabel jEliminar;
    private javax.swing.JTextField jEliminar_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jVolver;
    // End of variables declaration//GEN-END:variables
}
