/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author nicol
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setTitle("Menu Principal"); 
        initComponents();   
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bagregar_a = new javax.swing.JButton();
        Beliminar_a = new javax.swing.JButton();
        Bagregar_u = new javax.swing.JButton();
        Beliminar_u = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bagregar_a.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bagregar_a.setText("Agregar Articulo");
        Bagregar_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bagregar_aActionPerformed(evt);
            }
        });

        Beliminar_a.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Beliminar_a.setText("Eliminar Articulo");
        Beliminar_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Beliminar_aActionPerformed(evt);
            }
        });

        Bagregar_u.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bagregar_u.setText("Agregar Usuario");
        Bagregar_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bagregar_uActionPerformed(evt);
            }
        });

        Beliminar_u.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Beliminar_u.setText("Eliminar Usuario");
        Beliminar_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Beliminar_uActionPerformed(evt);
            }
        });

        Bsalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Agregar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Eliminar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Bagregar_a)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Beliminar_a)
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Beliminar_u)
                            .addComponent(Bagregar_u, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bagregar_a)
                    .addComponent(Bagregar_u)
                    .addComponent(jButton1))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Beliminar_a)
                    .addComponent(Beliminar_u)
                    .addComponent(jButton2))
                .addGap(56, 56, 56)
                .addComponent(Bsalir)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bagregar_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar_aActionPerformed
  
            Agregar_articulo in = new Agregar_articulo();
            in.setVisible(true);
            dispose();
        
        
    }//GEN-LAST:event_Bagregar_aActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        // TODO add your handling code here:
        
            login in = new login();
            in.setVisible(true);
            dispose();
        
    }//GEN-LAST:event_BsalirActionPerformed

    private void Bagregar_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bagregar_uActionPerformed
        // TODO add your handling code here:
        Agregar_usuario in = new Agregar_usuario();
        in.setVisible(true);
        dispose();    
    }//GEN-LAST:event_Bagregar_uActionPerformed

    private void Beliminar_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Beliminar_uActionPerformed
        // TODO add your handling code here:
        
        Eliminar_usuario in = new Eliminar_usuario();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_Beliminar_uActionPerformed

    private void Beliminar_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Beliminar_aActionPerformed
        // TODO add your handling code here:
        Elminar_articulo in = new Elminar_articulo();
        in.setVisible(true);
        dispose();
       
        
    }//GEN-LAST:event_Beliminar_aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            Agregar_pedido in = new Agregar_pedido();
            in.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Eliminar_pedido in = new Eliminar_pedido();
            in.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregar_a;
    private javax.swing.JButton Bagregar_u;
    private javax.swing.JButton Beliminar_a;
    private javax.swing.JButton Beliminar_u;
    private javax.swing.JButton Bsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
